//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFridayThe13th.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestFridayThe13th.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;user_name&quot;: &quot;JP&quot;,
        ///	&quot;follower_count&quot;: 100,
        ///	&quot;something&quot;, &quot;no_way&quot;,
        ///	&quot;don&apos;t_do_it&quot;, &quot;ok&quot;
        ///}.
        /// </summary>
        internal static string json_camelize {
            get {
                return ResourceManager.GetString("json_camelize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;glossary&quot;: {
        ///        &quot;title&quot;: &quot;example glossary&quot;,
        ///		&quot;GlossDiv&quot;: {
        ///            &quot;title&quot;: &quot;S&quot;,
        ///			&quot;GlossList&quot;: {
        ///                &quot;GlossEntry&quot;: {
        ///                    &quot;ID&quot;: &quot;SGML&quot;,
        ///					&quot;SortAs&quot;: &quot;SGML&quot;,
        ///					&quot;GlossTerm&quot;: &quot;Standard Generalized Markup Language&quot;,
        ///					&quot;Abbrev&quot;: &quot;ISO 8879:1986&quot;,
        ///					&quot;GlossDef&quot;: {
        ///                        &quot;para&quot;: &quot;A meta-markup language, used to create markup languages such as DocBook.&quot;,
        ///						&quot;GlossSeeAlso&quot;: [&quot;GML&quot;, &quot;XML&quot;]
        ///                    },
        ///					&quot;GlossSee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json_example1 {
            get {
                return ResourceManager.GetString("json_example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;menu&quot;: {
        ///  &quot;id&quot;: &quot;file&quot;,
        ///	&quot;value&quot;: &quot;File&quot;,
        ///  &quot;popup&quot;: {
        ///    &quot;menuitems&quot;: [
        ///      {&quot;value&quot;: &quot;New&quot;, &quot;onclick&quot;: &quot;CreateNewDoc()&quot;},
        ///      {&quot;value&quot;: &quot;Open&quot;, &quot;onclick&quot;: &quot;OpenDoc()&quot;},
        ///      {&quot;value&quot;: &quot;Close&quot;, &quot;onclick&quot;: &quot;CloseDoc()&quot;}
        ///    ]
        ///  }
        ///}}.
        /// </summary>
        internal static string json_example2 {
            get {
                return ResourceManager.GetString("json_example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;widget&quot;: {
        ///    &quot;debug&quot;: &quot;on&quot;,
        ///    &quot;window&quot;: {
        ///        &quot;title&quot;: &quot;Sample Konfabulator Widget&quot;,
        ///        &quot;width&quot;: 500,
        ///        &quot;height&quot;: 600
        ///    }
        ///}}    .
        /// </summary>
        internal static string json_example3 {
            get {
                return ResourceManager.GetString("json_example3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;web-app&quot;: {
        ///  &quot;servlet&quot;: [   
        ///    {
        ///      &quot;servlet-class&quot;: &quot;org.cofax.cds.CDSServlet&quot;,
        ///      &quot;init-param&quot;: {
        ///        &quot;configGlossary:adminEmail&quot;: &quot;ksm@pobox.com&quot;,
        ///        &quot;maxUrlLength&quot;: 500}},
        ///    {
        ///      &quot;servlet-name&quot;: &quot;cofaxEmail&quot;,
        ///      &quot;init-param&quot;: {
        ///      &quot;mailHost&quot;: &quot;mail1&quot;,
        ///      &quot;mailHostOverride&quot;: &quot;mail2&quot;}},
        ///    {
        ///      &quot;servlet-name&quot;: &quot;fileServlet&quot;,
        ///      &quot;servlet-class&quot;: &quot;org.cofax.cds.FileServlet&quot;},
        ///    {
        ///      &quot;servlet-name&quot;: &quot;cofaxTools&quot;,
        ///      &quot;servlet-class&quot;: &quot;org.cofax [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json_example4 {
            get {
                return ResourceManager.GetString("json_example4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///        {&quot;id&quot;: &quot;Open&quot;},
        ///        {&quot;id&quot;: &quot;OpenNew&quot;, &quot;true&quot;: &quot;Open New&quot;},
        ///        null,
        ///        {&quot;id&quot;: false},
        ///        {&quot;id&quot;: &quot;ZoomOut&quot;, &quot;label&quot;: true},
        ///        true,
        ///        {&quot;id&quot;: &quot;Mute&quot;},
        ///        null
        ///  ].
        /// </summary>
        internal static string json_example5 {
            get {
                return ResourceManager.GetString("json_example5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;a&quot;: &quot;you are a \&quot;silly\&quot; person.&quot;,
        ///   &quot;b&quot;: &quot;my name is &apos;JP&apos;&quot;
        ///   &quot;c&quot;: &quot;testing a new \n line.&quot;
        ///}.
        /// </summary>
        internal static string json_strings {
            get {
                return ResourceManager.GetString("json_strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;div&quot;: &quot;\u00f7&quot;,
        ///	&quot;sigma&quot;: &quot;\u03A3&quot;,
        ///	&quot;inf&quot;: &quot;\u101C&quot;
        ///}.
        /// </summary>
        internal static string json_unicode {
            get {
                return ResourceManager.GetString("json_unicode", resourceCulture);
            }
        }
    }
}
